/**
 * 把單筆 HistoryEntry 匯出成可讀性高的 Markdown 文件，
 * 適合貼到部落格、Notion、討論區分享。
 */

import type { HistoryEntry } from '../types';

function bold(s: string): string {
  return s ? `**${s}**` : '—';
}

function listOrDash(arr: string[] | undefined): string {
  return arr && arr.length > 0 ? arr.join(', ') : '—';
}

function escapeMd(s: string): string {
  // 簡單跳脫：避免 Markdown 特殊字元干擾
  return s.replace(/([*_`~|])/g, '\\$1');
}

export function exportEntryAsMarkdown(e: HistoryEntry): string {
  const s = e.state;
  const date = new Date(e.savedAt).toLocaleString('zh-TW');
  const stars = e.result?.rating ? '★'.repeat(e.result.rating) + '☆'.repeat(5 - e.result.rating) : '';

  const lines: string[] = [];

  // 標題
  lines.push(`# ${escapeMd(e.title || '未命名')}`);
  lines.push('');

  // Metadata 表格
  lines.push('| 欄位 | 值 |');
  lines.push('| --- | --- |');
  lines.push(`| 建立時間 | ${date} |`);
  if (e.result?.rating) lines.push(`| 評分 | ${stars} (${e.result.rating}/5) |`);
  if (e.result?.audioUrl) lines.push(`| 音檔連結 | [${e.result.audioUrl}](${e.result.audioUrl}) |`);
  lines.push(`| 語言 | ${s.language} |`);
  lines.push(`| 曲風 | ${s.genre} |`);
  lines.push(`| 能量 | ${s.energy || '—'} |`);
  lines.push(`| 情緒 | ${listOrDash(s.moods)} |`);
  lines.push(`| 樂器 | ${listOrDash(s.instruments)} |`);
  lines.push(`| 人聲 | ${s.voiceCloneActive ? 'Voice Clone' : listOrDash(s.vocals)} |`);
  lines.push(`| 紋理 | ${listOrDash(s.textures)} |`);
  lines.push(`| Negatives | ${listOrDash(s.negatives)} |`);
  lines.push(`| BPM / Key | ${s.bpm || '—'} / ${s.musicKey || '—'} |`);
  lines.push(`| 段落骨架 | ${s.structureName || '—'} |`);
  lines.push(`| 抗切割感 | ${s.cohesion ? '✓' : '—'} |`);
  if (s.extra) lines.push(`| 額外關鍵字 | ${escapeMd(s.extra)} |`);
  lines.push('');

  // 評分筆記
  if (e.result?.notes) {
    lines.push('## 📝 評分筆記');
    lines.push('');
    lines.push(`> ${e.result.notes.split('\n').join('\n> ')}`);
    lines.push('');
  }

  // 創作背景
  if (s.lyricsTheme || s.lyricsKeywords || s.lyricsStory) {
    lines.push('## 🎨 創作背景');
    lines.push('');
    if (s.lyricsTheme) lines.push(`- **主題**：${escapeMd(s.lyricsTheme)}`);
    if (s.lyricsKeywords) lines.push(`- **關鍵字**：${escapeMd(s.lyricsKeywords)}`);
    if (s.lyricsStory) {
      lines.push(`- **故事**：`);
      lines.push('');
      lines.push(`  ${s.lyricsStory.split('\n').join('\n  ')}`);
    }
    lines.push('');
  }

  // Style Prompt
  lines.push('## 📤 Style Prompt');
  lines.push('');
  lines.push('```');
  lines.push(e.stylePrompt);
  lines.push('```');
  lines.push('');

  // Lyrics
  lines.push('## 📝 Lyrics');
  lines.push('');
  lines.push('```');
  lines.push(e.lyricsPrompt);
  lines.push('```');
  lines.push('');

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by ${bold('Suno Prompt Generator')} · ${date}*`);

  return lines.join('\n');
}

/** 安全的檔名：去除非法字元並截斷。 */
export function safeFilename(title: string, ext: string): string {
  const cleaned = title.replace(/[\\/:*?"<>|]/g, '').trim() || 'song';
  const dateStr = new Date().toISOString().slice(0, 10);
  return `${cleaned.slice(0, 50)}-${dateStr}.${ext}`;
}
