import type { V6Preset } from './types';

export const V6_PRESETS: readonly V6Preset[] = [
  {
    id: 'mandarin-cinematic-ballad',
    name: '華語電影感抒情',
    shortDescription: '親密敘事逐步展開成寬銀幕副歌。',
    tags: ['華語', '抒情', 'cinematic'],
    brief: {
      language: '繁體中文',
      genre: 'Mandarin cinematic pop ballad',
      moods: ['bittersweet', 'tender', 'hopeful'],
      energy: 'slow burn to cathartic peak',
      theme: '在失去之後，從熟悉的城市風景重新找到前進的勇氣',
      keywords: ['雨夜', '街燈', '告別', '晨光'],
      story: '以具體場景推進關係的離散與釋懷，避免抽象口號。',
      additionalDirection: '電影式景深、清楚旋律線與克制留白；最後副歌才完整釋放。',
    },
    bpm: 78,
    key: 'A major',
    instruments: ['felt piano', 'warm strings', 'restrained drums', 'subtle electric guitar'],
    textures: ['wide cinematic ambience', 'organic room tone'],
    sections: [
      { tag: 'Intro', description: '建立雨夜空間與主題動機', lyrics: '', energy: 'very low', instrumentation: 'felt piano, distant ambience' },
      { tag: 'Verse 1', description: '近距離敘事，讓細節先於情緒', lyrics: '', energy: 'low', instrumentation: 'piano, sparse low strings' },
      { tag: 'Pre-Chorus', description: '和聲與節奏開始向上牽引', lyrics: '', energy: 'medium', instrumentation: 'rising strings, restrained tom pulse' },
      { tag: 'Chorus', description: '清楚 hook 與第一次情緒展開', lyrics: '', energy: 'high', instrumentation: 'full strings, drums, supportive guitar' },
      { tag: 'Bridge', description: '抽掉節奏，帶出關係轉折', lyrics: '', energy: 'medium', instrumentation: 'voice and piano, suspended strings' },
      { tag: 'Final Chorus', description: '旋律延伸與寬銀幕式最終釋放', lyrics: '', energy: 'peak', instrumentation: 'full band, soaring strings, backing vocals' },
      { tag: 'Outro', description: '回收主題動機並留下餘韻', lyrics: '', energy: 'low', instrumentation: 'piano motif, string harmonics' },
    ],
    vocalDirection: { mode: 'vocal', descriptors: ['intimate Mandarin lead', 'clear diction', 'restrained vibrato', 'soaring but not belted final chorus'], useVoiceClone: false },
    energyArc: {
      summary: '從耳語般的近景，經兩次漸進堆疊，在最後副歌達到唯一峰值。',
      stages: [
        { section: 'Intro / Verse 1', level: 'low', direction: '保持呼吸與空白' },
        { section: 'Pre-Chorus / Chorus', level: 'high', direction: '增加寬度，不過早全開' },
        { section: 'Bridge', level: 'medium', direction: '抽離後重建張力' },
        { section: 'Final Chorus', level: 'peak', direction: '完整樂團與和聲釋放' },
      ],
    },
    recommendation: { model: 'v6', workflow: 'create', rationale: '需要精準服從敘事、動態與長線編曲。' },
    avoid: ['generic power ballad clichés', 'constant full-volume drums', 'excessive vocal runs', 'abrupt EDM drop'],
  },
  {
    id: 'urban-synth-pop',
    name: '都會 synth-pop',
    shortDescription: '霓虹夜行、俐落節拍與帶距離感的流行 hook。',
    tags: ['synth-pop', '都會', 'night drive'],
    brief: {
      language: '繁體中文', genre: 'urban synth-pop', moods: ['cool', 'restless', 'romantic'], energy: 'steady dance pulse with a bright chorus lift',
      theme: '午夜城市裡若即若離的關係', keywords: ['霓虹', '計程車', '已讀', '天台'], story: '一段只在深夜成立的關係，天亮前必須做出選擇。',
      additionalDirection: '現代、乾淨、低頻有控制；副歌以旋律和音色抬升，而非巨大 drop。',
    },
    bpm: 112, key: 'F# minor',
    instruments: ['analog polysynth', 'punchy drum machine', 'synth bass', 'muted electric guitar'],
    textures: ['neon gloss', 'gated ambience', 'sidechained pads'],
    sections: [
      { tag: 'Intro', description: '用可辨識 synth motif 定調', lyrics: '', energy: 'low', instrumentation: 'filtered arpeggio, city ambience' },
      { tag: 'Verse', description: '節奏緊湊的城市細節', lyrics: '', energy: 'medium', instrumentation: 'dry beat, synth bass, muted guitar' },
      { tag: 'Pre-Chorus', description: '拉開空間並延長和聲', lyrics: '', energy: 'high', instrumentation: 'open hats, widening pads' },
      { tag: 'Chorus', description: '簡潔且可立即記住的 hook', lyrics: '', energy: 'peak', instrumentation: 'bright polysynth stack, full beat' },
      { tag: 'Post-Chorus', description: '器樂 hook 延續動能', lyrics: '', energy: 'high', instrumentation: 'vocal chop used sparingly, lead synth' },
      { tag: 'Outro', description: '像車流遠去般收束', lyrics: '', energy: 'low', instrumentation: 'filtered motif, delayed guitar' },
    ],
    vocalDirection: { mode: 'vocal', descriptors: ['cool close-mic lead', 'rhythmic phrasing', 'understated verses', 'layered chorus doubles'], useVoiceClone: false },
    energyArc: { summary: '維持夜行脈搏，靠頻譜與層次在副歌抬升。', stages: [
      { section: 'Verse', level: 'medium', direction: '乾、近、律動明確' }, { section: 'Pre-Chorus', level: 'high', direction: '展寬並留出吸氣點' }, { section: 'Chorus', level: 'peak', direction: '亮度與疊唱達峰值' },
    ] },
    recommendation: { model: 'v6', workflow: 'create', rationale: '精準控制 groove、音色層次與流行結構。' },
    avoid: ['festival EDM drop', 'retro pastiche overload', 'muddy low end', 'over-sung verses'],
  },
  {
    id: 'live-band',
    name: '現場樂團',
    shortDescription: '保留人味、互動與舞台動態的完整演奏。',
    tags: ['live', 'band', 'organic'],
    brief: {
      language: '繁體中文', genre: 'live pop rock band', moods: ['earnest', 'warm', 'uplifting'], energy: 'human push-and-pull with a communal finale',
      theme: '一起走過低潮後重新上路', keywords: ['公路', '排練室', '朋友', '合唱'], story: '從個人低谷走向夥伴共同承接的現場時刻。',
      additionalDirection: '像同一空間內的真實樂手演奏；允許細微速度與力度呼吸。',
    },
    bpm: 98, key: 'D major', instruments: ['live drums', 'electric bass', 'two electric guitars', 'upright piano'], textures: ['room microphones', 'amp air', 'natural bleed'],
    sections: [
      { tag: 'Count-in / Intro', description: '立即建立現場感與吉他 riff', lyrics: '', energy: 'medium', instrumentation: 'stick count, guitar riff, room mics' },
      { tag: 'Verse', description: '樂團讓位給敘事與律動', lyrics: '', energy: 'medium', instrumentation: 'rim-click drums, bass, clean guitar' },
      { tag: 'Chorus', description: '全團打開但保留動態', lyrics: '', energy: 'high', instrumentation: 'open drums, overdriven guitars, piano' },
      { tag: 'Instrumental Break', description: '樂手互相回應而非炫技', lyrics: '', energy: 'high', instrumentation: 'guitar and piano call-response' },
      { tag: 'Final Chorus', description: '觀眾可加入的共同高潮', lyrics: '', energy: 'peak', instrumentation: 'full band, gang vocals, cymbal lift' },
    ],
    vocalDirection: { mode: 'vocal', descriptors: ['natural live lead', 'conversational verses', 'controlled grit', 'communal gang-vocal finale'], useVoiceClone: false },
    energyArc: { summary: '以演奏力度和樂手互動自然增長，避免網格式機械堆疊。', stages: [
      { section: 'Intro / Verse', level: 'medium', direction: '先建立 pocket 與人味' }, { section: 'Chorus', level: 'high', direction: '打開鼓組和吉他' }, { section: 'Final Chorus', level: 'peak', direction: '加入群唱與舞台感' },
    ] },
    recommendation: { model: 'v6', workflow: 'create', rationale: '正式生成能更好維持全曲樂團一致性。' },
    avoid: ['quantized robotic drums', 'sample-replaced sterility', 'wall-of-sound throughout', 'virtuoso soloing'],
  },
  {
    id: 'anime-ending',
    name: '動畫片尾',
    shortDescription: '收束故事、保留想念，最後留下下一集的光。',
    tags: ['動畫', 'ending', 'J-pop'],
    brief: {
      language: '繁體中文', genre: 'anime ending theme, orchestral J-pop', moods: ['nostalgic', 'gentle', 'quietly hopeful'], energy: 'soft reflection into an emotional final refrain',
      theme: '冒險暫停後，角色在夜空下記住彼此的約定', keywords: ['星空', '車站', '約定', '明天'], story: '像一集結束後的角色內心旁白，回看當日失落並預告仍會前行。',
      additionalDirection: '旋律有動畫片尾辨識度，情緒真誠但不煽情；尾奏適合接工作人員名單。',
    },
    bpm: 86, key: 'E major', instruments: ['acoustic guitar', 'piano', 'chamber strings', 'soft rock drums', 'glockenspiel'], textures: ['twilight warmth', 'gentle tape bloom'],
    sections: [
      { tag: 'Intro', description: '短小主題動機，立即進入片尾氛圍', lyrics: '', energy: 'low', instrumentation: 'acoustic guitar, glockenspiel' },
      { tag: 'Verse', description: '角色視角的具體回憶', lyrics: '', energy: 'low', instrumentation: 'guitar, piano, brushed drums' },
      { tag: 'Chorus', description: '溫柔但清楚的核心約定', lyrics: '', energy: 'high', instrumentation: 'strings, full soft drums, harmony vocal' },
      { tag: 'Bridge', description: '短暫轉暗，承認未解決的情緒', lyrics: '', energy: 'medium', instrumentation: 'piano, cello, suspended cymbal' },
      { tag: 'Final Refrain', description: '回到希望並延伸尾奏', lyrics: '', energy: 'peak', instrumentation: 'full ensemble, counter-melody strings' },
      { tag: 'Credits Outro', description: '讓主題旋律在字幕中繼續呼吸', lyrics: '', energy: 'low', instrumentation: 'guitar motif, glockenspiel, strings' },
    ],
    vocalDirection: { mode: 'vocal', descriptors: ['youthful clear lead', 'gentle emotional restraint', 'precise Mandarin diction', 'light harmony stacks'], useVoiceClone: false },
    energyArc: { summary: '低彩度回望，在 final refrain 短暫綻放，再平穩進入字幕尾奏。', stages: [
      { section: 'Verse', level: 'low', direction: '像內心旁白' }, { section: 'Chorus', level: 'high', direction: '旋律打開但不吶喊' }, { section: 'Final Refrain / Outro', level: 'peak', direction: '先綻放再柔和退場' },
    ] },
    recommendation: { model: 'v6', workflow: 'create', rationale: '適合精準維持旋律、故事收束與尾奏比例。' },
    avoid: ['hyperactive idol arrangement', 'comic sound effects', 'overly tragic belting', 'hard stop ending'],
  },
  {
    id: 'lofi-instrumental',
    name: 'lo-fi 純音樂',
    shortDescription: '低干擾、可循環，帶細微生活質地的專注背景。',
    tags: ['lo-fi', 'instrumental', 'focus'],
    brief: {
      language: '無歌詞', genre: 'lo-fi instrumental hip-hop', moods: ['calm', 'dusty', 'reflective'], energy: 'low and even with subtle micro-variation',
      theme: '深夜書桌旁的安靜專注', keywords: ['檯燈', '雨聲', '筆記', '凌晨'], story: '無敘事歌詞，以重複動機和細微變奏形成陪伴感。',
      additionalDirection: '可無縫循環、不要搶注意力；保留鼓點人味與和聲小瑕疵。',
    },
    bpm: 72, key: 'C minor', instruments: ['dusty electric piano', 'soft boom-bap drums', 'round bass', 'muted jazz guitar'], textures: ['vinyl dust', 'rain ambience', 'tape wobble'],
    sections: [
      { tag: 'Intro Loop', description: '以環境聲和和弦建立可循環世界', lyrics: '', energy: 'very low', instrumentation: 'rain, filtered electric piano' },
      { tag: 'Main Groove A', description: '主節奏與短動機', lyrics: '', energy: 'low', instrumentation: 'soft drums, bass, electric piano' },
      { tag: 'Variation B', description: '以和弦轉位和小型反旋律變化', lyrics: '', energy: 'medium', instrumentation: 'muted guitar, altered drum ghost notes' },
      { tag: 'Breakdown', description: '短暫抽掉鼓組，避免疲勞', lyrics: '', energy: 'very low', instrumentation: 'electric piano, rain, tape stop texture' },
      { tag: 'Loop Return', description: '自然回到開頭可銜接位置', lyrics: '', energy: 'low', instrumentation: 'main groove with reduced ending fill' },
    ],
    vocalDirection: { mode: 'instrumental' },
    energyArc: { summary: '低能量平臺，以微變奏而非高潮維持注意力。', stages: [
      { section: 'Main Groove', level: 'low', direction: '穩定且不侵入' }, { section: 'Variation', level: 'medium', direction: '只增加一個新元素' }, { section: 'Loop Return', level: 'low', direction: '回到可循環狀態' },
    ] },
    recommendation: { model: 'v6-mini', workflow: 'create', rationale: '結構精簡，適合快速產生多個可用 groove 草稿。' },
    avoid: ['prominent vocal samples', 'dramatic risers', 'busy drum fills', 'bright piercing lead'],
  },
  {
    id: 'film-score',
    name: '電影配樂',
    shortDescription: '以動機、配器與動態服務畫面，不依賴歌曲式副歌。',
    tags: ['score', 'cinematic', 'instrumental'],
    brief: {
      language: '無歌詞', genre: 'cinematic film score', moods: ['tense', 'awe-struck', 'resolute'], energy: 'patient thematic build into a controlled climax',
      theme: '主角穿越廢墟，在黎明看見仍值得守護的事物', keywords: ['廢墟', '地平線', '犧牲', '重生'], story: '從孤立與不確定，逐步揭露核心主題，最後不是勝利而是堅定選擇。',
      additionalDirection: '以兩至三音核心動機統一全曲；重視畫面空間、轉場與可剪輯節點。',
    },
    bpm: 64, key: 'D minor', instruments: ['low strings', 'solo cello', 'French horns', 'granular synth', 'deep percussion'], textures: ['vast air', 'subtle pulse', 'metallic resonance'],
    sections: [
      { tag: 'Atmospheric Opening', description: '空間與核心動機的碎片', lyrics: '', energy: 'very low', instrumentation: 'granular air, low strings, distant metal' },
      { tag: 'Theme Statement', description: '由獨奏樂器首次清楚呈現動機', lyrics: '', energy: 'low', instrumentation: 'solo cello, soft string bed' },
      { tag: 'Development', description: '節奏脈搏與和聲壓力逐漸增加', lyrics: '', energy: 'medium', instrumentation: 'ostinato strings, low pulse, restrained percussion' },
      { tag: 'Climax', description: '完整主題與銅管重量交會', lyrics: '', energy: 'peak', instrumentation: 'full strings, horns, deep percussion, synth support' },
      { tag: 'Aftermath', description: '留下選擇後的代價與餘韻', lyrics: '', energy: 'low', instrumentation: 'solo cello, decaying resonance' },
    ],
    vocalDirection: { mode: 'instrumental' },
    energyArc: { summary: '長線耐心堆疊，峰值集中且之後保留後果感。', stages: [
      { section: 'Opening / Theme', level: 'low', direction: '優先建立動機與空間' }, { section: 'Development', level: 'medium', direction: '以脈搏和配器密度增壓' }, { section: 'Climax', level: 'peak', direction: '完整主題只在此處出現' }, { section: 'Aftermath', level: 'low', direction: '迅速抽離重量' },
    ] },
    recommendation: { model: 'v6', workflow: 'create', rationale: '需要長線主題一致性、配器控制與精準動態。' },
    avoid: ['trailer braams every bar', 'pop song chorus structure', 'constant percussion', 'sentimental piano clichés'],
  },
  {
    id: 'experimental-mashup',
    name: 'experimental mashup',
    shortDescription: '讓異質來源各司其職，以共享動機建立新語法。',
    tags: ['experimental', 'mashup', 'hybrid'],
    brief: {
      language: '依來源素材', genre: 'experimental hybrid mashup', moods: ['uncanny', 'playful', 'volatile'], energy: 'fragmented tension resolving into a coherent hybrid peak',
      theme: '兩個不相容的聲音世界在碰撞後找到共同脈搏', keywords: ['切片', '錯位', '變形', '融合'], story: '先明確展示差異，再透過節奏、音高或音色轉譯讓來源產生共同語法。',
      additionalDirection: '來源角色必須清楚，轉場要有因果；意外感不能犧牲可辨識結構。',
    },
    bpm: 124, key: 'A minor', instruments: ['source-dependent samples', 'modular synth', 'hybrid percussion', 'processed bass'], textures: ['granular edits', 'spectral morphing', 'hard contrast'],
    sections: [
      { tag: 'Source A Exposition', description: '先讓來源 A 以近原貌建立身份', lyrics: '', energy: 'medium', instrumentation: 'source A dominant, minimal support' },
      { tag: 'Source B Interruption', description: '來源 B 以對比方式闖入', lyrics: '', energy: 'high', instrumentation: 'source B dominant, contrasting rhythm' },
      { tag: 'Deconstruction', description: '切片並尋找共享音高或節奏單位', lyrics: '', energy: 'medium', instrumentation: 'granular fragments, sparse pulse' },
      { tag: 'Hybrid Drop', description: '兩來源在共同 groove 中融合', lyrics: '', energy: 'peak', instrumentation: 'interlocked source motifs, hybrid drums, bass' },
      { tag: 'Mutated Reprise', description: '以交換後的音色角色重現開頭', lyrics: '', energy: 'high', instrumentation: 'source A phrased like B and vice versa' },
    ],
    vocalDirection: { mode: 'vocal', descriptors: ['treat source vocals as identifiable motifs', 'preserve intelligibility at focal moments', 'use fragmentation rhythmically'], useVoiceClone: false },
    energyArc: { summary: '差異展示、拆解、融合，峰值來自關係成立而非單純音量。', stages: [
      { section: 'Expositions', level: 'medium', direction: '分開建立來源身份' }, { section: 'Deconstruction', level: 'medium', direction: '降低密度、凸顯共享元素' }, { section: 'Hybrid Drop', level: 'peak', direction: '融合後形成新 groove' }, { section: 'Reprise', level: 'high', direction: '交換角色證明融合成立' },
    ] },
    recommendation: { model: 'v6-wild', workflow: 'mashup', rationale: '需要更高意外度，且 workflow 應明確攜帶多來源角色。' },
    avoid: ['unstructured collage', 'simultaneous full-spectrum sources', 'random transitions', 'copyright-unclear source material'],
  },
];

export function getV6Preset(id: V6Preset['id']): V6Preset | undefined {
  return V6_PRESETS.find((preset) => preset.id === id);
}
