import type { LanguageInfo, ProviderConfig, Scenario, Section } from './types';

// ================= 曲風 =================
export const GENRES: Record<string, string> = {
  '華語抒情': 'mandarin emotional ballad, cinematic pop',
  '華語流行': 'mandarin contemporary pop',
  '華語搖滾': 'mandarin alternative rock',
  '華語民謠': 'mandarin indie folk',
  '華語嘻哈': 'mandarin hip hop, modern trap',
  '古風中國風': 'chinese traditional fusion, modern arrangement',
  'City Pop': 'japanese city pop, 80s funk-influenced',
  'Synthwave': 'synthwave, retro-futuristic 80s',
  'Lo-fi Hip Hop': 'lo-fi hip hop, jazzy chill beats',
  'Indie Pop': 'indie pop, dreamy jangly guitars',
  'Indie Folk': 'indie folk, intimate storytelling',
  'Dream Pop': 'dream pop, shoegaze textures',
  'K-Pop': 'k-pop, glossy hyper-pop production',
  'R&B / Soul': 'modern r&b, neo-soul',
  'Cinematic': 'cinematic orchestral score, epic',
  'Ambient': 'ambient, atmospheric soundscape',
  'EDM': 'festival EDM, big-room drop',
  'House': 'deep house, four-on-the-floor groove',
  'Bossa Nova': 'bossa nova, brazilian jazz',
  'Acoustic': 'acoustic singer-songwriter, intimate',
  'Pop Punk': 'pop punk, energetic distorted guitars',
  'Funk': 'funk, slap bass, tight horns',
};

// ================= 情緒 =================
export const MOODS: Record<string, string> = {
  '溫暖': 'warm',
  '悲傷': 'melancholic, bittersweet',
  '勵志': 'uplifting, inspiring',
  '懷舊': 'nostalgic',
  '浪漫': 'romantic, tender',
  '希望': 'hopeful, optimistic',
  '孤獨': 'lonely, introspective',
  '憤怒': 'angry, intense',
  '平靜': 'calm, peaceful',
  '夢幻': 'dreamy, ethereal',
  '活力': 'energetic, vibrant',
  '莊重': 'solemn, dignified',
  '歡樂': 'joyful, cheerful',
  '深情': 'heartfelt, emotional',
  '神祕': 'mysterious, dark',
  '緊張': 'tense, suspenseful',
};

// ================= 能量 =================
export const ENERGY: Record<string, string> = {
  '極低（冥想/環境）': 'very low energy, ambient, meditative',
  '低（抒情/沉思）': 'low energy, intimate',
  '中（穩定流動）': 'medium energy, steady groove',
  '中高（有推進感）': 'medium-high energy, driving rhythm',
  '高（動感/燃）': 'high energy, anthemic',
  '極高（爆發/嗨）': 'very high energy, explosive',
};

// ================= 樂器 =================
export const INSTRUMENTS: Record<string, string> = {
  '暖音鋼琴': 'warm piano',
  '氈式鋼琴(Felt Piano)': 'felt piano, intimate',
  '指彈原聲吉他': 'fingerpicked acoustic guitar',
  '刷弦原聲吉他': 'strummed acoustic guitar',
  '破音電吉他': 'overdriven electric guitar',
  '清音電吉他': 'clean electric guitar, chorus effect',
  '立式低音貝斯': 'warm upright bass',
  '電貝斯': 'electric bass, groovy',
  '808 Sub Bass': '808 sub bass',
  '刷扣鼓組': 'brushed drums',
  '緊湊鼓組': 'tight drum kit',
  '電子鼓': 'punchy electronic drums',
  '鼓機': 'drum machine',
  '弦樂': 'lush strings',
  '弦樂四重奏': 'string quartet',
  '管弦樂團': 'full orchestra, cinematic swells',
  '復古合成器': 'vintage analog synth, slightly detuned',
  '氛圍墊音': 'lush atmospheric pads',
  '電影感效果': 'cinematic risers and impacts',
  '二胡': 'erhu, expressive',
  '古箏': 'guzheng, plucked',
  '竹笛': 'chinese bamboo flute',
  '薩克斯風': 'smooth saxophone',
  '小號': 'muted trumpet',
  '管風琴': 'hammond organ',
  '音樂盒': 'music box, celesta',
  '口琴': 'harmonica',
  '烏克麗麗': 'ukulele, bright',
  '黑膠鼓點': 'dusty boom-bap drums',
};

// ================= 人聲 =================
export const VOCALS: Record<string, string> = {
  '女聲(柔/氣音)': 'soft female vocals, breathy delivery',
  '女聲(高亢)': 'powerful female vocals, soaring belt',
  '女聲(中音/磁性)': 'smoky female alto, intimate',
  '男聲(低沉/磁性)': 'deep male baritone vocals',
  '男聲(清亮/抒情)': 'clear male tenor vocals, emotive',
  '男聲(沙啞)': 'raspy male vocals',
  '童聲合唱': "children's choir, innocent harmonies",
  '雙人對唱': 'male and female duet',
  '豐富和聲': 'rich layered backing harmonies',
  '全合唱團': 'full choir, anthemic',
  '饒舌': 'rap verses, flow-driven',
  '低語': 'intimate whisper vocals',
  '純音樂': 'instrumental, no vocals',
};

// ================= 製作紋理 =================
export const TEXTURES: Record<string, string> = {
  '電影感製作': 'cinematic production',
  '復古類比': 'vintage analog warmth, tape saturation',
  '現代亮麗': 'polished modern production',
  'Lo-fi 質感': 'lo-fi texture, vinyl crackle',
  '氛圍空間': 'atmospheric, spacious reverb',
  '緊湊乾淨': 'tight dry mix',
  '大編制層次': 'epic layered arrangement',
  '極簡編制': 'minimal arrangement, sparse',
  '貼耳近距收音': 'close-mic intimacy',
  '板式殘響': 'subtle plate reverb',
  '房間感': 'warm room ambience',
  '膠帶失真': 'tape distortion, lo-fi grit',
  '顆粒紋理': 'gritty texture, sandy',
  '原始情感核心': 'raw emotional core',
};

// ================= Negative Prompts =================
export const NEGATIVES: Record<string, string> = {
  '無 Autotune': 'no autotune',
  '無過度修音': 'no over-processing',
  '無合成器': 'no synths',
  '無鼓機': 'no drum machines',
  '無電子節拍': 'no electronic beats',
  '無大量殘響': 'no reverb wash',
  '無弦樂': 'no strings',
  '無人聲': 'no vocals',
  '無和聲': 'no backing vocals',
  '無破音': 'no distortion',
  '無饒舌': 'no rap',
  '無管樂': 'no horns',
  '無電吉他': 'no electric guitar',
  '無壓縮過度': 'no over-compression',
  '無爵士元素': 'no jazz elements',
  '無 EDM Drop': 'no EDM drop',
};

export const COHESION_KEYWORDS =
  'seamless transitions, cohesive arrangement, consistent groove throughout, flowing dynamics';

// ================= 語言 =================
export const LANGUAGES: Record<string, LanguageInfo> = {
  '華語(繁體)': { suno: 'mandarin chinese vocals', llm: '繁體中文（台灣用語）' },
  '華語(簡體)': { suno: 'mandarin chinese vocals', llm: '簡體中文' },
  '台語': { suno: 'taiwanese hokkien vocals', llm: '台語（漢字書寫）' },
  '粵語': { suno: 'cantonese vocals', llm: '粵語（廣東話）' },
  '英文': { suno: 'english vocals', llm: 'English' },
  '日文': { suno: 'japanese vocals', llm: '日文（漢字＋假名）' },
  '韓文': { suno: 'korean vocals', llm: '한국어 (Korean)' },
  '西班牙文': { suno: 'spanish vocals', llm: 'Español (Spanish)' },
  '中英混合': {
    suno: 'mandarin and english bilingual vocals',
    llm: '中文為主、副歌穿插英文',
  },
  '純樂器(無歌詞)': { suno: 'instrumental, no vocals', llm: '（無，純樂器）' },
};

// ================= 段落結構模板 =================
export const STRUCTURE_TEMPLATES: Record<string, Section[]> = {
  '標準流行 (V-PC-C-V-PC-C-B-C)': [
    { tag: 'Intro', desc: 'instrumental build, atmospheric', lyrics: '' },
    { tag: 'Verse 1', desc: 'intimate, sparse arrangement', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'rising tension, drums entering', lyrics: '' },
    { tag: 'Chorus', desc: 'full energy, soaring vocals', lyrics: '' },
    { tag: 'Verse 2', desc: 'maintaining momentum, slightly fuller', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'building further', lyrics: '' },
    { tag: 'Chorus', desc: 'bigger, layered harmonies', lyrics: '' },
    { tag: 'Bridge', desc: 'stripped back, emotional peak', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest moment, ad-libs and layers', lyrics: '' },
    { tag: 'Outro', desc: 'gradual fade, return to intro motif', lyrics: '' },
  ],
  '簡短版 (V-C-V-C-Outro)': [
    { tag: 'Verse 1', desc: 'intimate opening', lyrics: '' },
    { tag: 'Chorus', desc: 'full arrangement', lyrics: '' },
    { tag: 'Verse 2', desc: 'slightly fuller', lyrics: '' },
    { tag: 'Chorus', desc: 'with harmonies', lyrics: '' },
    { tag: 'Outro', desc: 'gentle fade', lyrics: '' },
  ],
  '抒情骨架 (Intro-V-C-V-C-B-C)': [
    { tag: 'Intro', desc: 'solo piano, ambient pad', lyrics: '' },
    { tag: 'Verse 1', desc: 'vocals with piano only', lyrics: '' },
    { tag: 'Chorus', desc: 'strings swelling, emotional lift', lyrics: '' },
    { tag: 'Verse 2', desc: 'subtle percussion enters', lyrics: '' },
    { tag: 'Chorus', desc: 'full band, emotional climb', lyrics: '' },
    { tag: 'Bridge', desc: 'key change, vocal peak', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest moment, layered vocals', lyrics: '' },
    { tag: 'Outro', desc: 'fade to solo piano', lyrics: '' },
  ],
  '電子流行 Drop': [
    { tag: 'Intro', desc: 'synth pad, filter sweep', lyrics: '' },
    { tag: 'Verse 1', desc: 'minimal beat, atmospheric', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'build with riser, snare roll', lyrics: '' },
    { tag: 'Drop / Chorus', desc: 'big synth drop, energetic', lyrics: '' },
    { tag: 'Verse 2', desc: 'sustained energy', lyrics: '' },
    { tag: 'Drop / Chorus', desc: 'biggest moment', lyrics: '' },
    { tag: 'Outro', desc: 'filter out, fade', lyrics: '' },
  ],
  '搖滾骨架': [
    { tag: 'Intro', desc: 'guitar riff, building drums', lyrics: '' },
    { tag: 'Verse 1', desc: 'groove-driven, vocal-forward', lyrics: '' },
    { tag: 'Chorus', desc: 'full band, anthemic', lyrics: '' },
    { tag: 'Verse 2', desc: 'sustained intensity', lyrics: '' },
    { tag: 'Chorus', desc: 'big chorus, gang vocals', lyrics: '' },
    { tag: 'Solo', desc: 'guitar solo, melodic', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest energy', lyrics: '' },
    { tag: 'Outro', desc: 'drum hits ending', lyrics: '' },
  ],
  '極簡 (V-C)': [
    { tag: 'Verse', desc: 'intimate', lyrics: '' },
    { tag: 'Chorus', desc: 'full energy', lyrics: '' },
  ],
  '純樂器 (Loop)': [
    { tag: 'Intro', desc: 'main motif establishes', lyrics: '' },
    { tag: 'A Section', desc: 'main groove', lyrics: '' },
    { tag: 'B Section', desc: 'variation, contrast', lyrics: '' },
    { tag: 'A Section', desc: 'return to main groove', lyrics: '' },
    { tag: 'Outro', desc: 'loopable fade', lyrics: '' },
  ],
};

// ================= 情境範本 =================
export const SCENARIOS: Record<string, Scenario> = {
  '華語抒情慢歌': {
    desc: '經典抒情主歌-副歌，深情女聲',
    language: '華語(繁體)',
    genre: '華語抒情',
    moods: ['深情', '悲傷', '懷舊'],
    instruments: ['氈式鋼琴(Felt Piano)', '弦樂', '指彈原聲吉他'],
    vocals: ['女聲(柔/氣音)', '豐富和聲'],
    textures: ['電影感製作', '氛圍空間', '貼耳近距收音'],
    energy: '低（抒情/沉思）',
    bpm: '70',
    key: 'Am',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無 Autotune', '無大量殘響'],
    extra: 'emotional, heartbreak, soaring chorus',
  },
  '流行燃曲': {
    desc: '勵志正能量，副歌大編制',
    language: '華語(繁體)',
    genre: '華語流行',
    moods: ['勵志', '希望', '活力'],
    instruments: ['暖音鋼琴', '弦樂', '緊湊鼓組', '破音電吉他'],
    vocals: ['男聲(清亮/抒情)', '豐富和聲'],
    textures: ['大編制層次', '電影感製作'],
    energy: '高（動感/燃）',
    bpm: '100',
    key: 'D major',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 Autotune', '無過度修音'],
    extra: 'anthem, uplifting, triumphant',
  },
  '搖滾爆發': {
    desc: '硬派搖滾、燃系吉他主導',
    language: '華語(繁體)',
    genre: '華語搖滾',
    moods: ['憤怒', '活力'],
    instruments: ['破音電吉他', '電貝斯', '緊湊鼓組'],
    vocals: ['男聲(沙啞)', '豐富和聲'],
    textures: ['緊湊乾淨', '原始情感核心'],
    energy: '極高（爆發/嗨）',
    bpm: '140',
    key: 'E minor',
    structure: '搖滾骨架',
    negatives: ['無 Autotune', '無合成器'],
    extra: 'raw, gritty, gang vocals on chorus',
  },
  'Lo-fi 讀書背景': {
    desc: '純樂器、放鬆、可循環',
    language: '純樂器(無歌詞)',
    genre: 'Lo-fi Hip Hop',
    moods: ['平靜', '懷舊', '夢幻'],
    instruments: ['暖音鋼琴', '黑膠鼓點', '立式低音貝斯'],
    vocals: ['純音樂'],
    textures: ['Lo-fi 質感', '氛圍空間', '膠帶失真'],
    energy: '低（抒情/沉思）',
    bpm: '82',
    key: 'F major',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無 EDM Drop'],
    extra: 'study beats, mellow, jazzy chords, vinyl warmth',
  },
  '古風中國風': {
    desc: '國樂元素融合現代編曲',
    language: '華語(繁體)',
    genre: '古風中國風',
    moods: ['懷舊', '深情', '莊重'],
    instruments: ['古箏', '二胡', '竹笛', '弦樂', '暖音鋼琴'],
    vocals: ['女聲(柔/氣音)', '男聲(清亮/抒情)'],
    textures: ['電影感製作', '氛圍空間'],
    energy: '中（穩定流動）',
    bpm: '78',
    key: 'Am pentatonic',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無合成器', '無鼓機'],
    extra: 'chinese traditional fusion, poetic, ancient atmosphere',
  },
  'Indie 民謠': {
    desc: '個人創作、原聲、敘事',
    language: '華語(繁體)',
    genre: 'Indie Folk',
    moods: ['溫暖', '懷舊', '孤獨'],
    instruments: ['指彈原聲吉他', '口琴', '暖音鋼琴', '立式低音貝斯'],
    vocals: ['男聲(清亮/抒情)', '女聲(柔/氣音)'],
    textures: ['復古類比', '極簡編制', '房間感'],
    energy: '低（抒情/沉思）',
    bpm: '90',
    key: 'G major',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無合成器', '無 Autotune', '無鼓機'],
    extra: 'indie folk, warm, intimate storytelling',
  },
  '電影配樂': {
    desc: '管弦樂史詩感、純音樂',
    language: '純樂器(無歌詞)',
    genre: 'Cinematic',
    moods: ['神祕', '希望', '緊張', '莊重'],
    instruments: ['管弦樂團', '弦樂四重奏', '暖音鋼琴', '電影感效果'],
    vocals: ['純音樂'],
    textures: ['電影感製作', '大編制層次', '氛圍空間'],
    energy: '中高（有推進感）',
    bpm: '85',
    key: 'D minor',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無鼓機', '無合成器'],
    extra: 'epic, soundtrack, building emotional arc',
  },
  'City Pop 復古': {
    desc: '80年代日式都會流行',
    language: '日文',
    genre: 'City Pop',
    moods: ['懷舊', '浪漫', '夢幻'],
    instruments: ['清音電吉他', '電貝斯', '復古合成器', '薩克斯風', '緊湊鼓組'],
    vocals: ['女聲(中音/磁性)', '豐富和聲'],
    textures: ['復古類比', '現代亮麗'],
    energy: '中（穩定流動）',
    bpm: '108',
    key: 'F major 7',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 EDM Drop', '無 Autotune'],
    extra: '80s japanese city pop, smooth groove, jazzy chords',
  },
  'EDM 派對': {
    desc: '電子節拍、Drop 主導',
    language: '英文',
    genre: 'EDM',
    moods: ['活力', '歡樂'],
    instruments: ['復古合成器', '鼓機', '808 Sub Bass', '氛圍墊音'],
    vocals: ['女聲(高亢)'],
    textures: ['現代亮麗', '緊湊乾淨'],
    energy: '極高（爆發/嗨）',
    bpm: '128',
    key: 'A minor',
    structure: '電子流行 Drop',
    negatives: ['無原聲樂器', '無爵士元素'],
    extra: 'festival anthem, big-room drop, energetic',
  },
  '氛圍環境': {
    desc: '純音樂氛圍墊底，可冥想/工作',
    language: '純樂器(無歌詞)',
    genre: 'Ambient',
    moods: ['平靜', '夢幻', '神祕'],
    instruments: ['氛圍墊音', '氈式鋼琴(Felt Piano)', '弦樂'],
    vocals: ['純音樂'],
    textures: ['氛圍空間', '極簡編制'],
    energy: '極低（冥想/環境）',
    bpm: '65',
    key: 'C major',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無鼓機', '無破音'],
    extra: 'meditative, ethereal, evolving textures',
  },
};

// ================= LLM Providers =================
export const PROVIDERS: Record<string, ProviderConfig> = {
  openrouter: {
    name: 'OpenRouter（推薦）',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'anthropic/claude-sonnet-4.5',
    type: 'openai',
  },
  openai: {
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    type: 'openai',
  },
  anthropic: {
    name: 'Anthropic Direct',
    baseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-5-20250929',
    type: 'anthropic',
  },
  gemini: {
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModel: 'gemini-2.5-flash',
    type: 'gemini',
  },
};

// ================= 本地模板意象詞庫 =================
export const IMAGE_BANK: Record<string, string[]> = {
  '溫暖': ['陽光', '微風', '懷裡', '笑容', '燭光', '相依', '平凡', '安然'],
  '悲傷': ['雨夜', '影子', '破碎', '遠去', '沉默', '枯萎', '蒼白', '失落'],
  '勵志': ['晨曦', '彼岸', '翅膀', '勇敢', '綻放', '向前', '光芒', '蛻變'],
  '懷舊': ['巷口', '舊照', '夏天', '信箋', '斑駁', '斜陽', '曾經', '腳印'],
  '浪漫': ['星空', '心跳', '眼神', '擁抱', '溫柔', '緣分', '凝望', '守候'],
  '希望': ['黎明', '種子', '天空', '綻開', '等待', '答案', '可能', '未來'],
  '孤獨': ['深夜', '城市', '燈光', '獨行', '回聲', '空曠', '雨聲', '窗外'],
  '夢幻': ['雲端', '幻影', '迷霧', '彩虹', '星河', '漂浮', '倒影', '夢境'],
  '神祕': ['古老', '迷宮', '暗影', '低語', '未知', '符號', '鏡中', '邊界'],
  '活力': ['奔跑', '燃燒', '節拍', '汗水', '閃耀', '突破', '瘋狂', '前進'],
  '深情': ['心底', '誓言', '歲月', '輪廓', '守望', '牽掛', '凝結', '眷戀'],
  '歡樂': ['笑聲', '派對', '雀躍', '舞動', '輕快', '歡呼', '彩帶', '陽光'],
  '莊重': ['時光', '信仰', '山河', '歸屬', '肩膀', '傳承', '見證', '永恆'],
  '緊張': ['心跳', '倒數', '緊握', '邊緣', '閃電', '對峙', '屏息', '迫近'],
};
