/**
 * App 資料層 — re-export 主動版本的詞彙 + 應用層常數。
 *
 * Suno 版本特定資料（vocab / 限制 / builder）由 sunoVersions/ 管理；
 * 此檔案只保留與版本無關的應用資料：場景範本、段落骨架、LLM provider、本地詞庫。
 */

import type { Scenario, Section, ProviderConfig } from './types';
import { getActiveVersion } from './lib/sunoVersions';

// ───────── 從 active Suno 版本 re-export ─────────
const _v = getActiveVersion();
export const GENRES = _v.GENRES;
export const MOODS = _v.MOODS;
export const ENERGY = _v.ENERGY;
export const INSTRUMENTS = _v.INSTRUMENTS;
export const VOCALS = _v.VOCALS;
export const TEXTURES = _v.TEXTURES;
export const NEGATIVES = _v.NEGATIVES;
export const LANGUAGES = _v.LANGUAGES;
export const COHESION_KEYWORDS = _v.COHESION_KEYWORDS;

// ───────── 段落結構模板（版本無關） ─────────
export const STRUCTURE_TEMPLATES: Record<string, Section[]> = {
  '標準流行 (V-PC-C-V-PC-C-B-C)': [
    { tag: 'Intro', desc: 'instrumental build, atmospheric', lyrics: '' },
    { tag: 'Verse 1', desc: 'intimate, sparse arrangement', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'rising tension, drums entering', lyrics: '' },
    { tag: 'Chorus', desc: 'full energy, soaring vocals', lyrics: '' },
    { tag: 'Verse 2', desc: 'maintaining momentum, slightly fuller', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'building further', lyrics: '' },
    { tag: 'Chorus', desc: 'bigger, layered harmonies', lyrics: '' },
    { tag: 'Bridge', desc: 'stripped back, emotional peak', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest moment, ad-libs and layers', lyrics: '' },
    { tag: 'Outro', desc: 'gradual fade, return to intro motif', lyrics: '' },
  ],
  '簡短版 (V-C-V-C-Outro)': [
    { tag: 'Verse 1', desc: 'intimate opening', lyrics: '' },
    { tag: 'Chorus', desc: 'full arrangement', lyrics: '' },
    { tag: 'Verse 2', desc: 'slightly fuller', lyrics: '' },
    { tag: 'Chorus', desc: 'with harmonies', lyrics: '' },
    { tag: 'Outro', desc: 'gentle fade', lyrics: '' },
  ],
  '抒情骨架 (Intro-V-C-V-C-B-C)': [
    { tag: 'Intro', desc: 'solo piano, ambient pad', lyrics: '' },
    { tag: 'Verse 1', desc: 'vocals with piano only', lyrics: '' },
    { tag: 'Chorus', desc: 'strings swelling, emotional lift', lyrics: '' },
    { tag: 'Verse 2', desc: 'subtle percussion enters', lyrics: '' },
    { tag: 'Chorus', desc: 'full band, emotional climb', lyrics: '' },
    { tag: 'Bridge', desc: 'key change, vocal peak', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest moment, layered vocals', lyrics: '' },
    { tag: 'Outro', desc: 'fade to solo piano', lyrics: '' },
  ],
  '電子流行 Drop': [
    { tag: 'Intro', desc: 'synth pad, filter sweep', lyrics: '' },
    { tag: 'Verse 1', desc: 'minimal beat, atmospheric', lyrics: '' },
    { tag: 'Pre-Chorus', desc: 'build with riser, snare roll', lyrics: '' },
    { tag: 'Drop / Chorus', desc: 'big synth drop, energetic', lyrics: '' },
    { tag: 'Verse 2', desc: 'sustained energy', lyrics: '' },
    { tag: 'Drop / Chorus', desc: 'biggest moment', lyrics: '' },
    { tag: 'Outro', desc: 'filter out, fade', lyrics: '' },
  ],
  '搖滾骨架': [
    { tag: 'Intro', desc: 'guitar riff, building drums', lyrics: '' },
    { tag: 'Verse 1', desc: 'groove-driven, vocal-forward', lyrics: '' },
    { tag: 'Chorus', desc: 'full band, anthemic', lyrics: '' },
    { tag: 'Verse 2', desc: 'sustained intensity', lyrics: '' },
    { tag: 'Chorus', desc: 'big chorus, gang vocals', lyrics: '' },
    { tag: 'Solo', desc: 'guitar solo, melodic', lyrics: '' },
    { tag: 'Final Chorus', desc: 'biggest energy', lyrics: '' },
    { tag: 'Outro', desc: 'drum hits ending', lyrics: '' },
  ],
  '極簡 (V-C)': [
    { tag: 'Verse', desc: 'intimate', lyrics: '' },
    { tag: 'Chorus', desc: 'full energy', lyrics: '' },
  ],
  '純樂器 (Loop)': [
    { tag: 'Intro', desc: 'main motif establishes', lyrics: '' },
    { tag: 'A Section', desc: 'main groove', lyrics: '' },
    { tag: 'B Section', desc: 'variation, contrast', lyrics: '' },
    { tag: 'A Section', desc: 'return to main groove', lyrics: '' },
    { tag: 'Outro', desc: 'loopable fade', lyrics: '' },
  ],
};

// ───────── 情境範本（版本無關，但鍵需與 active 版本 vocab 對齊） ─────────
export const SCENARIOS: Record<string, Scenario> = {
  '華語抒情慢歌': {
    desc: '經典抒情主歌-副歌，深情女聲',
    language: '華語(繁體)',
    genre: '華語抒情',
    moods: ['深情', '悲傷', '懷舊'],
    instruments: ['氈式鋼琴(Felt Piano)', '弦樂', '指彈原聲吉他'],
    vocals: ['女聲(柔/氣音)', '豐富和聲'],
    textures: ['電影感製作', '氛圍空間', '貼耳近距收音'],
    energy: '低（抒情/沉思）',
    bpm: '70',
    key: 'Am',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無 Autotune', '無大量殘響'],
    extra: 'emotional, heartbreak, soaring chorus',
  },
  '流行燃曲': {
    desc: '勵志正能量，副歌大編制',
    language: '華語(繁體)',
    genre: '華語流行',
    moods: ['勵志', '希望', '活力'],
    instruments: ['暖音鋼琴', '弦樂', '緊湊鼓組', '破音電吉他'],
    vocals: ['男聲(清亮/抒情)', '豐富和聲'],
    textures: ['大編制層次', '電影感製作'],
    energy: '高（動感/燃）',
    bpm: '100',
    key: 'D major',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 Autotune', '無過度修音'],
    extra: 'anthem, uplifting, triumphant',
  },
  '搖滾爆發': {
    desc: '硬派搖滾、燃系吉他主導',
    language: '華語(繁體)',
    genre: '華語搖滾',
    moods: ['憤怒', '活力'],
    instruments: ['破音電吉他', '電貝斯', '緊湊鼓組'],
    vocals: ['男聲(沙啞)', '豐富和聲'],
    textures: ['緊湊乾淨', '原始情感核心'],
    energy: '極高（爆發/嗨）',
    bpm: '140',
    key: 'E minor',
    structure: '搖滾骨架',
    negatives: ['無 Autotune', '無合成器'],
    extra: 'raw, gritty, gang vocals on chorus',
  },
  'Lo-fi 讀書背景': {
    desc: '純樂器、放鬆、可循環',
    language: '純樂器(無歌詞)',
    genre: 'Lo-fi Hip Hop',
    moods: ['平靜', '懷舊', '夢幻'],
    instruments: ['暖音鋼琴', '黑膠鼓點', '立式低音貝斯'],
    vocals: ['純音樂'],
    textures: ['Lo-fi 質感', '氛圍空間', '膠帶失真'],
    energy: '低（抒情/沉思）',
    bpm: '82',
    key: 'F major',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無 EDM Drop'],
    extra: 'study beats, mellow, jazzy chords, vinyl warmth',
  },
  '古風中國風': {
    desc: '國樂元素融合現代編曲',
    language: '華語(繁體)',
    genre: '古風中國風',
    moods: ['懷舊', '深情', '莊重'],
    instruments: ['古箏', '二胡', '竹笛', '弦樂', '暖音鋼琴'],
    vocals: ['女聲(柔/氣音)', '男聲(清亮/抒情)'],
    textures: ['電影感製作', '氛圍空間'],
    energy: '中（穩定流動）',
    bpm: '78',
    key: 'Am pentatonic',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無合成器', '無鼓機'],
    extra: 'chinese traditional fusion, poetic, ancient atmosphere',
  },
  'Indie 民謠': {
    desc: '個人創作、原聲、敘事',
    language: '華語(繁體)',
    genre: 'Indie Folk',
    moods: ['溫暖', '懷舊', '孤獨'],
    instruments: ['指彈原聲吉他', '口琴', '暖音鋼琴', '立式低音貝斯'],
    vocals: ['男聲(清亮/抒情)', '女聲(柔/氣音)'],
    textures: ['復古類比', '極簡編制', '房間感'],
    energy: '低（抒情/沉思）',
    bpm: '90',
    key: 'G major',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無合成器', '無 Autotune', '無鼓機'],
    extra: 'indie folk, warm, intimate storytelling',
  },
  '電影配樂': {
    desc: '管弦樂史詩感、純音樂',
    language: '純樂器(無歌詞)',
    genre: 'Cinematic',
    moods: ['神祕', '希望', '緊張', '莊重'],
    instruments: ['管弦樂團', '弦樂四重奏', '暖音鋼琴', '電影感效果'],
    vocals: ['純音樂'],
    textures: ['電影感製作', '大編制層次', '氛圍空間'],
    energy: '中高（有推進感）',
    bpm: '85',
    key: 'D minor',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無鼓機', '無合成器'],
    extra: 'epic, soundtrack, building emotional arc',
  },
  'City Pop 復古': {
    desc: '80年代日式都會流行',
    language: '日文',
    genre: 'City Pop',
    moods: ['懷舊', '浪漫', '夢幻'],
    instruments: ['清音電吉他', '電貝斯', '復古合成器', '薩克斯風', '緊湊鼓組'],
    vocals: ['女聲(中音/磁性)', '豐富和聲'],
    textures: ['復古類比', '現代亮麗'],
    energy: '中（穩定流動）',
    bpm: '108',
    key: 'F major 7',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 EDM Drop', '無 Autotune'],
    extra: '80s japanese city pop, smooth groove, jazzy chords',
  },
  'EDM 派對': {
    desc: '電子節拍、Drop 主導',
    language: '英文',
    genre: 'EDM',
    moods: ['活力', '歡樂'],
    instruments: ['復古合成器', '鼓機', '808 Sub Bass', '氛圍墊音'],
    vocals: ['女聲(高亢)'],
    textures: ['現代亮麗', '緊湊乾淨'],
    energy: '極高（爆發/嗨）',
    bpm: '128',
    key: 'A minor',
    structure: '電子流行 Drop',
    negatives: ['無爵士元素'],
    extra: 'festival anthem, big-room drop, energetic',
  },
  '氛圍環境': {
    desc: '純音樂氛圍墊底，可冥想/工作',
    language: '純樂器(無歌詞)',
    genre: 'Ambient',
    moods: ['平靜', '夢幻', '神祕'],
    instruments: ['氛圍墊音', '氈式鋼琴(Felt Piano)', '弦樂'],
    vocals: ['純音樂'],
    textures: ['氛圍空間', '極簡編制'],
    energy: '極低（冥想/環境）',
    bpm: '65',
    key: 'C major',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無鼓機', '無破音'],
    extra: 'meditative, ethereal, evolving textures',
  },
  'K-Pop 偶像舞曲': {
    desc: 'K-pop 主流舞曲、女團能量',
    language: '韓文',
    genre: 'K-Pop',
    moods: ['活力', '歡樂', '浪漫'],
    instruments: ['復古合成器', '電貝斯', '緊湊鼓組', '氛圍墊音'],
    vocals: ['女聲(高亢)', '豐富和聲'],
    textures: ['現代亮麗', '緊湊乾淨'],
    energy: '高（動感/燃）',
    bpm: '118',
    key: 'B minor',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 Autotune'],
    extra: 'k-pop, glossy production, hook-driven, dance-pop',
  },
  'R&B 慢板': {
    desc: '都會 R&B、磁性女聲、深夜氛圍',
    language: '英文',
    genre: 'R&B / Soul',
    moods: ['浪漫', '深情', '神祕'],
    instruments: ['暖音鋼琴', '電貝斯', '黑膠鼓點', '氛圍墊音'],
    vocals: ['女聲(中音/磁性)', '低語'],
    textures: ['貼耳近距收音', '板式殘響'],
    energy: '低（抒情/沉思）',
    bpm: '78',
    key: 'D minor',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無 Autotune', '無破音'],
    extra: 'modern r&b, late-night, sensual, neo-soul',
  },
  '華語嘻哈': {
    desc: '華語饒舌、Trap 808 節拍',
    language: '華語(繁體)',
    genre: '華語嘻哈',
    moods: ['活力', '憤怒'],
    instruments: ['808 Sub Bass', '鼓機', '氛圍墊音'],
    vocals: ['饒舌', '男聲(沙啞)'],
    textures: ['緊湊乾淨', '原始情感核心'],
    energy: '中高（有推進感）',
    bpm: '85',
    key: 'F# minor',
    structure: '簡短版 (V-C-V-C-Outro)',
    negatives: ['無 Autotune', '無弦樂'],
    extra: 'modern trap, hard-hitting 808s, melodic flow',
  },
  'Synthwave 80s': {
    desc: '80年代復古未來感、霓虹夜',
    language: '英文',
    genre: 'Synthwave',
    moods: ['懷舊', '夢幻', '神祕'],
    instruments: ['復古合成器', '電子鼓', '氛圍墊音', '電貝斯'],
    vocals: ['女聲(中音/磁性)'],
    textures: ['復古類比', '氛圍空間'],
    energy: '中（穩定流動）',
    bpm: '105',
    key: 'C# minor',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無爵士元素'],
    extra: 'synthwave, retro-futuristic, neon nights, gated reverb drums',
  },
  'House 律動': {
    desc: 'Deep House 四四拍、純樂器',
    language: '純樂器(無歌詞)',
    genre: 'House',
    moods: ['活力', '浪漫'],
    instruments: ['電子鼓', '電貝斯', '復古合成器', '氛圍墊音'],
    vocals: ['純音樂'],
    textures: ['緊湊乾淨', '現代亮麗'],
    energy: '中高（有推進感）',
    bpm: '124',
    key: 'A minor',
    structure: '純樂器 (Loop)',
    negatives: ['無人聲', '無破音'],
    extra: 'deep house, four-on-the-floor, groovy, sunset vibes',
  },
  'Bossa Nova 咖啡': {
    desc: '巴西爵士、慵懶午後咖啡館',
    language: '英文',
    genre: 'Bossa Nova',
    moods: ['平靜', '浪漫', '懷舊'],
    instruments: ['指彈原聲吉他', '立式低音貝斯', '刷扣鼓組', '薩克斯風'],
    vocals: ['女聲(中音/磁性)'],
    textures: ['復古類比', '貼耳近距收音'],
    energy: '低（抒情/沉思）',
    bpm: '92',
    key: 'A major',
    structure: '簡短版 (V-C-V-C-Outro)',
    negatives: ['無破音', '無合成器'],
    extra: 'bossa nova, brazilian jazz, café atmosphere, smooth swing',
  },
  'Pop Punk 熱血': {
    desc: '青春龐克、熱血躁動',
    language: '英文',
    genre: 'Pop Punk',
    moods: ['活力', '勵志'],
    instruments: ['破音電吉他', '電貝斯', '緊湊鼓組'],
    vocals: ['男聲(清亮/抒情)', '豐富和聲'],
    textures: ['緊湊乾淨', '現代亮麗'],
    energy: '極高（爆發/嗨）',
    bpm: '160',
    key: 'D major',
    structure: '搖滾骨架',
    negatives: ['無 Autotune', '無合成器'],
    extra: 'pop punk, fast-paced, sing-along chorus, palm-muted verses',
  },
  'Funk 派對': {
    desc: 'Funk 律動、號管組、舞廳',
    language: '英文',
    genre: 'Funk',
    moods: ['歡樂', '活力'],
    instruments: ['電貝斯', '清音電吉他', '緊湊鼓組', '小號', '管風琴'],
    vocals: ['男聲(清亮/抒情)', '豐富和聲'],
    textures: ['復古類比', '緊湊乾淨'],
    energy: '高（動感/燃）',
    bpm: '110',
    key: 'E minor',
    structure: '標準流行 (V-PC-C-V-PC-C-B-C)',
    negatives: ['無 Autotune', '無合成器'],
    extra: 'funk, slap bass, tight horns, danceable groove',
  },
  'Dream Pop 迷幻': {
    desc: '夢幻流行、Shoegaze 質感',
    language: '英文',
    genre: 'Dream Pop',
    moods: ['夢幻', '懷舊', '孤獨'],
    instruments: ['清音電吉他', '氛圍墊音', '電貝斯', '電子鼓'],
    vocals: ['女聲(柔/氣音)', '低語'],
    textures: ['氛圍空間', '膠帶失真', '板式殘響'],
    energy: '低（抒情/沉思）',
    bpm: '95',
    key: 'F# major',
    structure: '簡短版 (V-C-V-C-Outro)',
    negatives: ['無 Autotune', '無破音'],
    extra: 'dream pop, shoegaze, hazy textures, washed-out vocals',
  },
  'Acoustic 純粹': {
    desc: '原聲創作、單人吉他敘事',
    language: '英文',
    genre: 'Acoustic',
    moods: ['溫暖', '深情', '希望'],
    instruments: ['指彈原聲吉他', '口琴', '立式低音貝斯'],
    vocals: ['男聲(清亮/抒情)'],
    textures: ['極簡編制', '貼耳近距收音', '房間感'],
    energy: '低（抒情/沉思）',
    bpm: '88',
    key: 'C major',
    structure: '簡短版 (V-C-V-C-Outro)',
    negatives: ['無合成器', '無 Autotune', '無鼓機'],
    extra: 'acoustic singer-songwriter, intimate, vulnerable',
  },
  '粵語金曲': {
    desc: '粵語經典抒情、廣東話深情',
    language: '粵語',
    genre: '華語抒情',
    moods: ['深情', '懷舊', '浪漫'],
    instruments: ['暖音鋼琴', '弦樂', '指彈原聲吉他', '薩克斯風'],
    vocals: ['男聲(低沉/磁性)', '豐富和聲'],
    textures: ['電影感製作', '貼耳近距收音'],
    energy: '低（抒情/沉思）',
    bpm: '72',
    key: 'C major',
    structure: '抒情骨架 (Intro-V-C-V-C-B-C)',
    negatives: ['無 Autotune', '無鼓機'],
    extra: 'classic cantopop ballad, 90s hk feel, smooth saxophone',
  },
  '童趣兒歌': {
    desc: '兒童合唱、歡樂簡單',
    language: '華語(繁體)',
    genre: 'Acoustic',
    moods: ['歡樂', '溫暖', '希望'],
    instruments: ['烏克麗麗', '音樂盒', '刷弦原聲吉他', '口琴'],
    vocals: ['童聲合唱', '豐富和聲'],
    textures: ['極簡編制', '房間感'],
    energy: '中（穩定流動）',
    bpm: '108',
    key: 'C major',
    structure: '簡短版 (V-C-V-C-Outro)',
    negatives: ['無破音', '無 EDM Drop', '無 Autotune'],
    extra: "playful children's song, joyful, singalong",
  },
};

// ───────── LLM Providers（與 Suno 版本無關） ─────────
export const PROVIDERS: Record<string, ProviderConfig> = {
  openrouter: {
    name: 'OpenRouter（推薦）',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'anthropic/claude-sonnet-4.5',
    type: 'openai',
  },
  openai: {
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o-mini',
    type: 'openai',
  },
  anthropic: {
    name: 'Anthropic Direct',
    baseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-5-20250929',
    type: 'anthropic',
  },
  gemini: {
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    defaultModel: 'gemini-2.5-flash',
    type: 'gemini',
  },
};

// ───────── 本地模板意象詞庫（版本無關） ─────────
export const IMAGE_BANK: Record<string, string[]> = {
  '溫暖': ['陽光', '微風', '懷裡', '笑容', '燭光', '相依', '平凡', '安然'],
  '悲傷': ['雨夜', '影子', '破碎', '遠去', '沉默', '枯萎', '蒼白', '失落'],
  '勵志': ['晨曦', '彼岸', '翅膀', '勇敢', '綻放', '向前', '光芒', '蛻變'],
  '懷舊': ['巷口', '舊照', '夏天', '信箋', '斑駁', '斜陽', '曾經', '腳印'],
  '浪漫': ['星空', '心跳', '眼神', '擁抱', '溫柔', '緣分', '凝望', '守候'],
  '希望': ['黎明', '種子', '天空', '綻開', '等待', '答案', '可能', '未來'],
  '孤獨': ['深夜', '城市', '燈光', '獨行', '回聲', '空曠', '雨聲', '窗外'],
  '夢幻': ['雲端', '幻影', '迷霧', '彩虹', '星河', '漂浮', '倒影', '夢境'],
  '神祕': ['古老', '迷宮', '暗影', '低語', '未知', '符號', '鏡中', '邊界'],
  '活力': ['奔跑', '燃燒', '節拍', '汗水', '閃耀', '突破', '瘋狂', '前進'],
  '深情': ['心底', '誓言', '歲月', '輪廓', '守望', '牽掛', '凝結', '眷戀'],
  '歡樂': ['笑聲', '派對', '雀躍', '舞動', '輕快', '歡呼', '彩帶', '陽光'],
  '莊重': ['時光', '信仰', '山河', '歸屬', '肩膀', '傳承', '見證', '永恆'],
  '緊張': ['心跳', '倒數', '緊握', '邊緣', '閃電', '對峙', '屏息', '迫近'],
};
